# python Libraries Assignment
# Array creation

In [1]:
# Import the NumPy library
import numpy as np
# Task 1: Create a numpy array of size 10, filled with zeros
array_zeros = np.zeros(10)
print("Task 1:", array_zeros)

Task 1: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
# Task 2: Create a numpy array with values ranging from 10 to 49 and set its datatype to float
array_float = np.arange(10, 50, dtype=float)
print("Task 2:", array_float)

Task 2: [10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


In [3]:
# Task 3: Create a numpy matrix of 2*2 integers, filled with ones
matrix_ones_int = np.ones((2, 2), dtype=int)
print("Task 3:", matrix_ones_int)

Task 3: [[1 1]
 [1 1]]


In [4]:
# Task 4: Create a numpy matrix of 3*2 float numbers, filled with ones
matrix_ones_float = np.ones((3, 2), dtype=float)
print("Task 4:", matrix_ones_float)

Task 4: [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [33]:
# Given matrix X
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Task 5: Create a new numpy array with the same shape and type as X, filled with ones
ones_like_X = np.ones_like(X)
print("Task 5:", ones_like_X)

Task 5: [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [34]:
# Task 6: Create a new numpy matrix with the same shape and type as X, filled with zeros
zeros_like_X = np.zeros_like(X)
print("Task 6:", zeros_like_X)

Task 6: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
# Task 7: Create a numpy matrix of 4*4 integers, filled with fives
matrix_fives = np.full((4, 4), 5, dtype=int)
print("Task 7:", matrix_fives)

Task 7: [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [35]:
# Task 8: Create a new numpy matrix with the same shape and type as X, filled with sevens
sevens_like_X = np.full_like(X, 7)
print("Task 8:", sevens_like_X)

Task 8: [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [9]:
# Task 9: Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere
identity_matrix = np.eye(3)
print("Task 9:", identity_matrix)

Task 9: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# Task 10: Create a numpy array, filled with 3 random integer values between 1 and 10
random_integers = np.random.randint(1, 11, 3)
print("Task 10:", random_integers)

Task 10: [5 2 4]


In [11]:
# Task 11: Create a 3*3*3 numpy matrix, filled with random float values
random_floats = np.random.rand(3, 3, 3)
print("Task 11:", random_floats)

Task 11: [[[0.2215614  0.92525611 0.99361924]
  [0.00559532 0.14851623 0.2885781 ]
  [0.31609801 0.50702335 0.70709549]]

 [[0.71758603 0.80281887 0.92249631]
  [0.43236782 0.22191571 0.96818938]
  [0.9212234  0.65506808 0.35966677]]

 [[0.50609077 0.00987291 0.08965938]
  [0.13325948 0.13040419 0.37930676]
  [0.6820953  0.15858014 0.43022285]]]


In [12]:
# Task 12: Create a numpy array with numbers from 1 to 10
array_1_to_10 = np.arange(1, 11)
print("Task 12:", array_1_to_10)

Task 12: [ 1  2  3  4  5  6  7  8  9 10]


In [13]:
# Task 13: Create a numpy array with the odd numbers between 1 to 10
array_odd_numbers = np.arange(1, 11, 2)
print("Task 13:", array_odd_numbers)

Task 13: [1 3 5 7 9]


In [14]:
# Task 14: Create a numpy array with numbers from 1 to 10, in descending order
array_descending = np.arange(10, 0, -1)
print("Task 14:", array_descending)

Task 14: [10  9  8  7  6  5  4  3  2  1]


In [15]:
# Task 15: Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("Task 15:", matrix_0_to_8)

Task 15: [[0 1 2]
 [3 4 5]
 [6 7 8]]


# Array indexing

In [16]:
# Task 1: Given the X numpy array, show its first element
X = np.array(['A', 'B', 'C', 'D', 'E'])
print("Task 1:", X[0])


Task 1: A


In [17]:
# Task 2: Given the X numpy array, show its last element
print("Task 2:", X[-1])

Task 2: E


In [18]:
# Task 3: Given the X numpy array, show its first three elements
print("Task 3:", X[:3])

Task 3: ['A' 'B' 'C']


In [19]:
# Task 4: Given the X numpy array, show all middle elements
print("Task 4:", X[1:-1])

Task 4: ['B' 'C' 'D']


In [20]:
# Task 5: Given the X numpy array, show the elements in reverse position
print("Task 5:", X[::-1])

Task 5: ['E' 'D' 'C' 'B' 'A']


In [21]:
# Task 6: Given the X numpy array, show the elements in an odd position
print("Task 6:", X[::2])

Task 6: ['A' 'C' 'E']


In [22]:
# Task 7: Given the X numpy matrix, show the first row’s elements
Y = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
print("Task 7:", Y[0])

Task 7: [1 2 3 4]


In [23]:
# Task 8: Given the X numpy matrix, show the last row elements
print("Task 8:", Y[-1])

Task 8: [13 14 15 16]


In [24]:
# Task 9: Given the X numpy matrix, show the first element on the first row
print("Task 9:", Y[0, 0])

Task 9: 1


In [25]:
# Task 10: Given the X numpy matrix, show the last element on the last row
print("Task 10:", Y[-1, -1])

Task 10: 16


In [26]:
# Task 11: Given the X numpy matrix, show the first two elements on the first two rows
print("Task 11:", Y[:2, :2])

Task 11: [[1 2]
 [5 6]]


In [27]:
# Task 12: Given the X numpy matrix, show the last two elements on the last two rows
print("Task 12:", Y[-2:, -2:])

Task 12: [[11 12]
 [15 16]]


# Array manipulation

In [28]:
# Task 1: Convert the given integer numpy array to float
X = np.array([-5, -3, 0, 10, 40])
X_float = X.astype(float)
print("Task 1:", X_float)

Task 1: [-5. -3.  0. 10. 40.]


In [29]:
# Task 2: Reverse the given numpy array through indexing
X_reversed = X[::-1]
print("Task 2:", X_reversed)

Task 2: [40 10  0 -3 -5]


In [30]:
# Task 3: Given the X numpy array, set the fifth element equal to 1
X_task3 = np.zeros(10)
X_task3[4] = 1
print("Task 3:", X_task3)

Task 3: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [31]:
# Task 4: Given the X numpy matrix, change the last row with all 1
X_task4 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
X_task4[-1] = 1
print("Task 4:", X_task4)

Task 4: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


In [32]:
# Task 5: Given the X numpy matrix, add 5 to every element
X_task5 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
X_task5 += 5
print("Task 5:", X_task5)

Task 5: [[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
